version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - gofiber
  - samber
  - slogfiber
  - slogformatter
ignoreWords:
  - andybalholm
  - crashme
  - fxamacker
  - goleak
  - philhofer
  - tinylib
  - valyala
import: []
